/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author jeissoncc
 */
public class jpagenda extends javax.swing.JPanel {
    
    conexion conn;
   
    
    
    public jpagenda() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpagendar = new javax.swing.JPanel();
        lbfecha = new javax.swing.JLabel();
        lbcliente = new javax.swing.JLabel();
        lbid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btbuscar = new javax.swing.JButton();
        lbservicio = new javax.swing.JLabel();
        txtfecha = new javax.swing.JFormattedTextField();
        lbdireccion = new javax.swing.JLabel();
        txtcliente = new javax.swing.JLabel();
        lbtelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JLabel();
        lbcontacto = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        etiqueta = new javax.swing.JLabel();
        lbobserva = new javax.swing.JLabel();
        txtobserva = new javax.swing.JTextField();
        btcancelacion = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        btprint = new javax.swing.JButton();
        lbconsecutivo = new javax.swing.JLabel();
        txtconsecutivo = new javax.swing.JTextField();
        btsalvar1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtdireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btsalvar2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(630, 470));
        setPreferredSize(new java.awt.Dimension(630, 470));
        setSize(new java.awt.Dimension(630, 470));

        jpagendar.setBackground(new java.awt.Color(255, 255, 255));
        jpagendar.setMinimumSize(new java.awt.Dimension(630, 470));
        jpagendar.setPreferredSize(new java.awt.Dimension(630, 470));
        jpagendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbfecha.setText("fecha:");
        jpagendar.add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbcliente.setText("Cliente:");
        jpagendar.add(lbcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbid.setText("ID:");
        jpagendar.add(lbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 20));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jpagendar.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 139, -1));

        btbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btbuscar.setForeground(new java.awt.Color(51, 182, 215));
        btbuscar.setText("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });
        jpagendar.add(btbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 40));

        lbservicio.setText("Servicio:");
        jpagendar.add(lbservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });
        jpagendar.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 128, 30));

        lbdireccion.setText("Direccion:");
        jpagendar.add(lbdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 450, 20));

        lbtelefono.setText("Telefono:");
        jpagendar.add(lbtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 64, -1));

        txttelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 430, 20));

        lbcontacto.setText("Contacto:");
        jpagendar.add(lbcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtcontacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txtcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 430, 20));
        jpagendar.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 10));
        jpagendar.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 200, 10));

        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Datos del Servicio");
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpagendar.add(etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 201, -1));

        lbobserva.setText("Observaciones:");
        jpagendar.add(lbobserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txtobserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobservaActionPerformed(evt);
            }
        });
        jpagendar.add(txtobserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 580, 70));

        btcancelacion.setBackground(new java.awt.Color(255, 255, 255));
        btcancelacion.setForeground(new java.awt.Color(51, 182, 215));
        btcancelacion.setText("Cancelar");
        btcancelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelacionActionPerformed(evt);
            }
        });
        jpagendar.add(btcancelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, 40));

        btexit.setBackground(new java.awt.Color(255, 255, 255));
        btexit.setForeground(new java.awt.Color(51, 182, 215));
        btexit.setText("Salir");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });
        jpagendar.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 60, 40));

        btprint.setBackground(new java.awt.Color(255, 255, 255));
        btprint.setForeground(new java.awt.Color(51, 182, 215));
        btprint.setText("Imprimir");
        jpagendar.add(btprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 90, 40));

        lbconsecutivo.setText("Consecutivo:");
        jpagendar.add(lbconsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 30));

        txtconsecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsecutivoActionPerformed(evt);
            }
        });
        jpagendar.add(txtconsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 160, 30));

        btsalvar1.setBackground(new java.awt.Color(255, 255, 255));
        btsalvar1.setForeground(new java.awt.Color(51, 182, 215));
        btsalvar1.setText("Agregar");
        btsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvar1ActionPerformed(evt);
            }
        });
        jpagendar.add(btsalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 80, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpagendar.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 530, -1));

        txtdireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 430, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Servicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jpagendar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 590, 80));

        btsalvar2.setBackground(new java.awt.Color(255, 255, 255));
        btsalvar2.setForeground(new java.awt.Color(51, 182, 215));
        btsalvar2.setText("Guardar");
        btsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvar2ActionPerformed(evt);
            }
        });
        jpagendar.add(btsalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        SqlUsuarios modSql  = new SqlUsuarios();
         Clientes    mod     = new Clientes(); 
         
         String ids = new String(txtid.getText());
         int id = Integer.parseInt(ids);
         
         modSql.existeCliente(id);
         
        txtcliente.setText(mod.getRazon_social());
        txtcontacto.setText(mod.getResponsable());
        txtdireccion.setText(mod.getDireccion());
        txttelefono.setText(mod.getTelefono());
         
         
         
    }//GEN-LAST:event_btbuscarActionPerformed

    private void txtobservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservaActionPerformed

    private void btcancelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcancelacionActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btexitActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void txtconsecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsecutivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsecutivoActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvar1ActionPerformed
                SqlUsuarios modSql  = new SqlUsuarios();
                usuarios    mod     = new usuarios(); 
                                           
    }//GEN-LAST:event_btsalvar1ActionPerformed

    private void btsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsalvar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btcancelacion;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btprint;
    private javax.swing.JButton btsalvar1;
    private javax.swing.JButton btsalvar2;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpagendar;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JLabel lbconsecutivo;
    private javax.swing.JLabel lbcontacto;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbobserva;
    private javax.swing.JLabel lbservicio;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel txtcliente;
    private javax.swing.JTextField txtconsecutivo;
    private javax.swing.JLabel txtcontacto;
    private javax.swing.JLabel txtdireccion;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtobserva;
    private javax.swing.JLabel txttelefono;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
