/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.util.ArrayList;


/**
 *
 * @author jeissoncc
 */
public class jpeuser extends javax.swing.JPanel {
    conexion conn;
    /**
     * Creates new form jpeuser
     */
    public jpeuser() {
        initComponents();       
    } 
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btexiteuser = new javax.swing.JButton();
        btactualizauser = new javax.swing.JButton();
        btsaveepeuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        bteliminaeuser1 = new javax.swing.JButton();
        jcbuser = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btexiteuser.setBackground(new java.awt.Color(255, 255, 255));
        btexiteuser.setForeground(new java.awt.Color(51, 182, 215));
        btexiteuser.setText("Salir");
        btexiteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexiteuserActionPerformed(evt);
            }
        });
        jPanel1.add(btexiteuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 60, 40));

        btactualizauser.setBackground(new java.awt.Color(255, 255, 255));
        btactualizauser.setForeground(new java.awt.Color(51, 182, 215));
        btactualizauser.setText("Actualizar");
        btactualizauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizauserActionPerformed(evt);
            }
        });
        jPanel1.add(btactualizauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 40));

        btsaveepeuser.setBackground(new java.awt.Color(255, 255, 255));
        btsaveepeuser.setForeground(new java.awt.Color(51, 182, 215));
        btsaveepeuser.setText("Guardar");
        btsaveepeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveepeuserActionPerformed(evt);
            }
        });
        jPanel1.add(btsaveepeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 200, 40));

        jLabel1.setText("Identificación: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 182, 215));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 620, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 160, 30));

        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, 20));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, 30));

        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 210, 30));

        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 570, 30));

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, -1));

        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, -1));

        jLabel8.setText("Contraseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel9.setText("Rol:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel10.setText("Usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, -1));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 240, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 182, 215));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Adicionar Usuario");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 620, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, -1));

        jLabel12.setText("Identificación: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 30));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, 30));

        jLabel13.setText("Nombre");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, 20));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 182, 215)));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 410, 30));

        jLabel15.setText("Rol:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 30));

        bteliminaeuser1.setBackground(new java.awt.Color(255, 255, 255));
        bteliminaeuser1.setForeground(new java.awt.Color(51, 182, 215));
        bteliminaeuser1.setText("Eliminar");
        bteliminaeuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminaeuser1ActionPerformed(evt);
            }
        });
        jPanel1.add(bteliminaeuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 90, 40));

        jcbuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbuserActionPerformed(evt);
            }
        });
        jPanel1.add(jcbuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 200, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btexiteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexiteuserActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btexiteuserActionPerformed

    private void btactualizauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizauserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btactualizauserActionPerformed

    private void btsaveepeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveepeuserActionPerformed
            SqlUsuarios modSql  = new SqlUsuarios();
            usuarios    mod     = new usuarios(); 
                                     
            String ids = new String(txtid.getText());
            String nombre = new String(txtnombres.getText());
            String apellido = new String(txtapellido.getText());
            String password = new String(txtpassword.getText());
            String email = new String(txtemail.getText());
            String user = new String(txtuser.getText());
            String direccion = new String(txtdireccion.getText());           
            String tel = new String(txttelefono.getText());   
            
            
              
            int id = Integer.parseInt(ids);
           
            
            
            
            mod.setId(id);
            mod.setNombre(nombre);
            mod.setApellido(apellido);
            mod.setPassword(password);
            mod.setEmail(email);
            mod.setUsuario(user);
            mod.setDireccion(direccion);
            mod.setTelefono(tel);        
           
            
            modSql.registrar(mod);
            
            limpiar();
               
    }//GEN-LAST:event_btsaveepeuserActionPerformed

    private void bteliminaeuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminaeuser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bteliminaeuser1ActionPerformed

    private void jcbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbuserActionPerformed

private void limpiar() {
            
            txtid.setText("");
            txtapellido.setText("");
            txtdireccion.setText("");
            txtemail.setText("");
            txtnombres.setText("");
            txtpassword.setText("");
            txttelefono.setText("");
            txtuser.setText("");
            
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btactualizauser;
    private javax.swing.JButton bteliminaeuser1;
    private javax.swing.JButton btexiteuser;
    private javax.swing.JButton btsaveepeuser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JComboBox<String> jcbuser;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
